services:
  - type: web
    name: randevu-sistemi
    env: java
    plan: free
    buildCommand: "./mvnw clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: JAVA_HOME
        value: /opt/render/project/.sdkman/candidates/java/current