services:
  - type: web
    name: randevu-sistemi
    env: java
    plan: free
    buildCommand: "mvn clean install"
    startCommand: "java -jar target/*.jar"
    envVars:
      - key: JAVA_VERSION
        value: 17